### ISSUE TITLE
A problem about Vagrant 

### ISSUE THREAD

**Issue by tyy0402** [NCSU-Libraries/ocracoke#14]
After I installed vagrant and vagrant-vbguest, 
`vagrant -v`shows "Vagrant 2.1.4"
while `vagrant -h` shows ```Plugin vagrant-vbguest is not installed. Install it with: vagrant plugin install vagrant-vbguest vagrant-triggers```
When I enter the ocracoke and `vagrant up`, it still shows ```Plugin vagrant-vbguest is not installed. Install it with: vagrant plugin install vagrant-vbguest vagrant-triggers```
Then I tried `vagrant plugin install vagrant-vbguest vagrant-triggers` and `vagrant up`, it shows 
```
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.16.0)'!
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Fetching: bundler-1.16.4.gem (100%)
Fetching: vagrant-triggers-0.5.3.gem (100%)
Installed the plugin 'vagrant-triggers (0.5.3)'!
```
and  `vagrant up` again, 
```
WARNING: Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

  vagrant plugin uninstall vagrant-triggers

Note that the community plugin `vagrant-triggers` and the core trigger feature
in Vagrant do not have compatible syntax.

To disable this warning, set the environment variable `VAGRANT_USE_VAGRANT_TRIGGERS`.
Plugin vagrant-vbguest is not installed. Install it with:
vagrant plugin install vagrant-vbguest vagrant-triggers
```
was showed.
How can I install  vagrant-vbguest correctly?

**Comment by tyy0402** [comment]
I use ubuntu

**Comment by tyy0402** [comment]
I can use `vagrant -h` outside the file of ocracoke.

**Comment by jronallo** [comment]
More recent versions of Vagrant include triggers so the plugin is no longer needed. I'll need to update the Vagrantfile.

**Comment by tyy0402** [comment]
Thanks a lot ! I figure out this problem https://github.com/dotless-de/vagrant-vbguest/issues/306
